apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapexplorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapexplorer
  template:
    metadata:
      labels:
        app: sapexplorer
    spec:
      containers:
        - name: sapexplorer
          #--image: sapexplorer:latest
          #--imagePullPolicy: Never
          image: ${{ secrets.ECR_REGISTRY  }}/sapexplorer:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: aws-ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sapexplorer-service
spec:
  type: LoadBalancer
  selector:
    app: sapexplorer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sapexplorer-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /postgres/all
            backend:
              service:
                name: sapexplorer-service
                port:
                  number: 8080
          - pathType: Prefix
            path: /postgres/upload-files
            backend:
              service:
                name: sapexplorer-service
                port:
                  number: 8080
