apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapexplorer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sapexplorer
  template:
    metadata:
      labels:
        app: sapexplorer
    spec:
      containers:
        - name: sapexplorer
          #--image: sapexplorer:latest
          #--imagePullPolicy: Never
          image: 503561426655.dkr.ecr.eu-west-1.amazonaws.com/aws_ecr_demo_repo:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: aws-ecr-secret
