name: sap explorer CI/CD Pipeline 

on:
  push:
    branches:
      - main
env:
  AWS_REGION: eu-west-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: my-repo
      
      - name: Verify Directory Structure
        run: |
         echo "000000000000000000000000000000"
         echo ${{ env.AWS_ACCESS_KEY_ID }}
         echo ${{ secrets.AWS_ACCESS_KEY_ID }}
         echo "000000000000000000000000000000"
         ls -R my-repo
         pwd
         echo "===================================="
         cd my-repo
         pwd
         ls -xlt

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build JAR
        run: |
          cd my-repo
          ls -xlt
          pwd
          cd backend/sap_explorer
          mvn clean package -DskipTests
        #working-directory: $(pwd)/backend/sap-explorer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        env:
          AWS_DEFAULT_REGION:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_SESSION_TOKEN:
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
          echo ${{ env.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          cd my-repo
          ls -xlt
          pwd
          cd backend/sap_explorer
          docker build -t sap-explorer:latest .
          docker images
          echo ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
          docker tag sap-explorer:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:sap-explorer
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:sap-explorer

  
      - name: Apply Kubernetes Manifests
        run: |
          cd my-repo
          ls -xlt
          pwd
          kubectl apply -f k8/
